# version: '3.8' # 이 라인은 삭제해도 됩니다.
services:
  db:
    image: mysql:8.0
    platform: linux/arm64  # <--- arm64 플랫폼 명시
    container_name: walkinggo-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: walkinggo
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64  # <--- arm64 플랫폼 명시 (build 하위가 아니라 app 서비스 바로 아래)
    container_name: walkinggo-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/walkinggo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
volumes:
  db-data: