services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    container_name: walkinggo-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: walkinggo
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: walkinggo-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/walkinggo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
volumes:
  db-data: